### ISSUE TITLE
SimpleAuth Also

### ISSUE THREAD

**Issue by BlindTail** [ecoron/PurePerms#1]
Regarding https://github.com/PurePlugins/PurePerms/pull/91

If this fix works for PurePerms; would you also please fork and make a similar set of changes to SimpleAuth? 

I think it is experiencing the same problem with getUniqueId()

**Comment by ecoron** [comment]
yes i will check it

**Comment by BlindTail** [comment]
Thank you for looking at SimpleAuth! I hope you have success.

**Comment by ecoron** [comment]
there is a hopefully fixed version for PocketMine-MP 1.6
get the phar directly from here: 

https://github.com/ecoron/SimpleAuth/blob/master/SimpleAuth_v1.8.0.phar

this is not an official release for SimpleAuth, so adress issues directly to https://github.com/ecoron/SimpleAuth
